version: "3.7"

services:
  a1Golang:
    image: a1golang
    build:
      context: ./bin/a1
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    network_mode: "host"
  b1Golang:
    image: b1golang
    build:
      context: ./bin/b1
      dockerfile: Dockerfile
    links:
      - a1Golang
    ports:
      - "8081:8081"
    networks:
        - a1network
networks:
    a1network:
        driver: bridge
